apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  namespace: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: 809317209874.dkr.ecr.ap-south-1.amazonaws.com/portfolio:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: portfolio-email
              key: username
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: portfolio-email
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-svc
  namespace: portfolio
spec:
  type: ClusterIP
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 8080
